### ISSUE TITLE
Zenodo dataset has empty files

### ISSUE THREAD

**Issue by LukasMosser** [ProgrammerZXG/Cross-Domain-Foundation-Model-Adaptation#1]
Thank you for sharing this interesting work. I am trying to collect the data used here and found that some of these files have empty inputs or cannot be loaded. Please find attached a log file that highlights empty, input or label images or files not possible to load as the others in the same folder/dataset. 

Could you comment or update the datasets on Zenodo to make them complete?

[seisbase.log](https://github.com/user-attachments/files/18167229/seisbase.log)

**Comment by ProgrammerZXG** [comment]
Thank you very much for your question. By “empty” data here, are you referring to values of 0? In this geobody detection dataset, there are indeed some 0 values, but this does not actually affect the training. The presence of all-0 labels occurs because the input seismic images do not contain geobody features. Similarly, there are cases where the input seismic data have all-0 values, but this also does not significantly affect the training results since such inputs are very few. However, if you prefer, you can simply filter them out.

From the seislog file you provided, it can be seen that most cases involve labels with 0 values. As mentioned above, this happens when the input seismic data do not contain geological body information.

**Comment by LukasMosser** [comment]
Ok! Thanks for clarifying!
